---
title: "Genie"
author: "Dave Hein"
date: "7/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Packages
```{r}
library(tidyverse)
library(readxl)
library(survival)
library(survminer)
library(randomForest)
library(MASS)
```


# GENIE loading and cleaning 
```{r}
#load data
data_clinical_sample <- read.delim("C:/Users/Dave Work/OneDrive - University of Texas Southwestern/CBio Portal/First Cbioportal Project/GENIE_and_TCGA/data_clinical_sample.txt", comment.char="#")

data_clinical_patient <- read.delim("C:/Users/Dave Work/OneDrive - University of Texas Southwestern/CBio Portal/First Cbioportal Project/GENIE_and_TCGA/data_clinical_patient.txt", comment.char="#")

data_mutations_extended <- read.delim("C:/Users/Dave Work/OneDrive - University of Texas Southwestern/CBio Portal/First Cbioportal Project/GENIE_and_TCGA/data_mutations_extended.txt")

#just CRC
genie_samples <- data_clinical_sample %>% filter(ONCOTREE_CODE=="COAD" | ONCOTREE_CODE=="READ") 

#only want one sample per pt
genie_samples <-genie_samples[!duplicated(genie_samples$SAMPLE_ID),]

#joining sample and pt data
genie_all_clinical <-inner_join(genie_samples,data_clinical_patient,by="PATIENT_ID")

#Creating a variable for YACRC
genie_all_clinical$AGE_AT_SEQ_REPORT <- as.numeric(as.character(genie_all_clinical$AGE_AT_SEQ_REPORT))
genie_all_clinical <- genie_all_clinical %>% mutate(AGE_AT_SEQ_REPORT,YACRC= ifelse(AGE_AT_SEQ_REPORT<50,1,0))


#making mutation columns for pts

#selecting sample IDs of pts with colorectal
sampleIDS <- genie_all_clinical %>%  mutate(SAMPLE_ID,Tumor_Sample_Barcode=SAMPLE_ID) %>% select(Tumor_Sample_Barcode)
#selecting mutations that have corresponding sample IDs
mutations_to_keep <- right_join(data_mutations_extended, sampleIDS, by='Tumor_Sample_Barcode')
#Making a list of genes that are mutated in more than 1% of pts, then filtering 
genes <-as.data.frame(table(mutations_to_keep$Hugo_Symbol)) %>% arrange(desc(Freq)) %>% filter(Freq>56)
genelist<-as.character(genes$Var1)
genes<-genes%>%rename(Hugo_Symbol=Var1)

mutations_to_keep_2 <- right_join(mutations_to_keep, genes, by='Hugo_Symbol')
mutations_to_keep_3 <- mutations_to_keep_2 %>% select(Hugo_Symbol,Tumor_Sample_Barcode)
mutations_to_keep_3<-mutations_to_keep_3%>%rename(SAMPLE_ID=Tumor_Sample_Barcode)
clinical_to_keep <- genie_all_clinical %>% select(SAMPLE_ID,YACRC)

# Creating a df for random forest 
combined <- full_join(clinical_to_keep,mutations_to_keep_3,by='SAMPLE_ID')

pivoted<- combined %>% pivot_wider( names_from = Hugo_Symbol,values_from = Hugo_Symbol)

pivoted<- pivoted %>% mutate_all(as.character)

pivoted[pivoted=='NULL'] <- '0'

pivoted[pivoted != '0'] <- '1' 

pivoted <- pivoted %>% select(-'NA')

pivoted <- pivoted %>% mutate_all(as.factor)


#Trying to figure out why random forest keeps giving me errors
summary(pivoted)
pivoted %>% summarize(n())
colSums(is.na(pivoted))
pivoted <- na.omit(pivoted)
a = as.data.frame(colnames(pivoted)) %>% rename(Hugo_Symbol='colnames(pivoted)')%>%mutate(a=1)
b=full_join(a,genes,by='Hugo_Symbol')


```



# Random Forest 
```{r}

rf <-randomForest(factor(YACRC)~APC+ TP53+KRAS+PIK3CA+SMAD4+ KMT2D+ ATM+
FBXW7+ BRAF+ARID1A+SOX9+TCF7L2+ERBB4+ PTEN+ 
BRCA2+ NOTCH1+FAT1+RNF43+ ARID1B+CREBBP+KMT2A+
SMARCA4 +    NF1+ CTNNB1+MTOR+KMT2C+ EP300+ NOTCH3 +
KDR+ SETD2+ ALK+ CARD11+GNAS+NRAS+ATRX+ 
PIK3R1+ROS1+GNAQP1+PTCH1+ EPHA5+ FLT4+PTPRS+
PRKDC+ ASXL1+ TSC2+ARID2+ ERBB3+ SMO+ AMER1+
BCOR+ERBB2+ MSH6+RET+ ZFHX3+ B2M+ TET2+ 
MGA+ POLE+FGFR3+ AR+  RB1+ PDGFRA+CIC+
BRM1+ FLT1+PTPRT+ EGFR+EPHA3+ ATR+ SPEN+ 
AP3K1+DICER1+MED12+ BRCA1+ KMT2B+ KIT+ MET+
FANCA+ GRIN2A+TERT+GLI1+NTRK3+ RECQL4+ABL1+ 
KZF1+ MSH2+NOTCH2+SMAD2+ AXIN2+ HNF1A+ PTPRD+
KDM5A+ FLT3+BRD4+NSD1+IGF1R+ ANKRD11  +   POLD1+
MLH1+BLM+ BCORL1+AXL+ CDKN2A+TET1+ESR1+ 
EPHA7+ JAK3+PREX2+ TSC1+MAP2K4+NPM1+FGFR2+
NCOR1+ CDK12+ DNMT3A+ERCC5+ PIK3CG+SF3B1+ STK11+
PDGFRB+NOTCH4+CASP8+ CTCF+RPTOR+ SMAD3+
TCF3+EPHB1+ KDM5C+ CDH1+KDM6A+ NTRK1+ IRS2+ 
PALB2+ RICTOR+TGFBR2+BRIP1+ LRP1B+ FGFR1+ PIK3C2B    +
PLCG2+ DDR2+DOT1L+ JAK2+STAG2+ GLI2+RAD50+
NTRK2+ AKT1+SLX4+FGFR4+ FLCN+RBM10+ GNA11+
SH2B3+ JAK1+MITF+PRDM1+ SOX17+ TP53BP1+CSF1R+
GATA3+ ARAF+PTENP1+DNMT1+ IRS1+SMARCB1  +   TBX3+ 
CDC73+ DIS3+NBN+ AXIN1+ PARK2+ SETBP1+GLI3+ 
PMS2+TNFAIP3  +   KAT6A+ RAF1+MSH3+CSF3R+ PIK3C2G   + 
CBL+ CUX1+PAX5+PTPN11+RUNX1+ ETV1+TSHR+ 
WHSC1+ PMS1+BAP1+CHEK2+ ERCC2+ MPL+ RASA1+
FANCD2+MEF2B+ WT1+ COL7A1+ERCC4+ FOXP1+ MAP2K1    + 
MYCN+ASXL2+ KEAP1+ MST1R+ POLQ+RIF1+PIK3CB     +
BCL6+SDHA+SYNE1+ CIITA+ EZH2+MECOM+ WRN+
LATS2+ XPO1+INHBA+ HGF+ JUN+ MEN1+   
ARID5B+MRE11A+SOS1+DOCK8+ IDH1+INPPL1+QKI+
SRC+ VHL+ WHSC1L1   +  DNMT3B+ERG+ NCOA3+ PPP2R1A    +
SUFU+BARD1+ CYLD+FANCC+ HRAS+BMPR1A+ERCC3+
PGR+ RARA+AKT3+IL7R+NF2+ PPM1D+ RAD21+
MDC1+NFE2L2+PIK3CD+REL+ ZNF217+DAXX+ETV6+ 
MUTYH+ MYBL1+ PIK3R2+CDKN1B+STAT3+ ALOX12B  +   LATS1+
PRKCI+ SYK+ GATA2+ RPS6KA4   +  FANCM+ RFWD2 
,
                  ntree=10000,
                   data=pivoted,
                   na.action=na.pass)

importance(rf)
print(rf)




```




# Junk code
```{r}


#Introducing columns that represent muations in those genes for each patient
genie_all_clinical[c(genelist)] <- 0

#for loop that puts in 1 if gene mutated in a pt
#genielooptest <- genie_all_clinical

#for (row in 1:nrow(genielooptest)){
#  for (col in 14:ncol(genielooptest)){
#    if
#  }
#}


```